name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  pretty:
    name: format and lint
    strategy:
      matrix:
        platform: [ubuntu-latest]
        toolchain: [stable]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt
      - name: format
        run: cargo fmt --all -- --check
      - name: lint
        run: cargo clippy --all-targets --all-features -- -W clippy::pedantic -D warnings
  test:
    name: test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [1.64.0, stable]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: test
        run: cargo test
